version: '3.4'

services:
  meetingschedulerapi:
    image: meetingschedulerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"

    volumes:
      - type: bind
        source: .\meetingScheduler.db
        target: \app\meetingScheduler.db